version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql8-spark
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: spark_demo
      MYSQL_USER: xw
      MYSQL_PASSWORD: xwpwd
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
