version: '3'
services:
  spark-master:
    image: bitnami/spark:3.5.5  # 升级 Spark 版本
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-net

  spark-worker:
    image: bitnami/spark:3.5.5  # 升级 Spark 版本
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G  # 增加内存
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    networks:
      - spark-net

networks:
  spark-net:
    driver: bridge
